# Generated by Django 5.2.6 on 2025-09-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folderID',
            field=models.AutoField(db_column='FolderID', primary_key=True, serialize=False),
        ),
    ]
