# Generated by Django 5.2.6 on 2025-09-15 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folderID', models.AutoField(db_column='ClaimID', primary_key=True, serialize=False)),
                ('folderName', models.CharField(db_column='FolderName', max_length=255)),
            ],
            options={
                'db_table': 'Folder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnimeListEntry',
            fields=[
                ('animeListEntryID', models.AutoField(db_column='AnimeListEntryID', primary_key=True, serialize=False)),
                ('malID', models.IntegerField(db_column='MalID')),
                ('ImageURL', models.CharField(db_column='ImageURL', max_length=255)),
                ('mainTitle', models.CharField(db_column='MainTitle', max_length=255)),
                ('user', models.ForeignKey(db_column='User', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(db_column='Folder', on_delete=django.db.models.deletion.PROTECT, to='AnimeSearch.folder')),
            ],
            options={
                'db_table': 'AnimeListEntry',
                'managed': True,
            },
        ),
    ]
